<?php
$assignValue=$_MB['PP']['ppAssignValue'];
echo 	"CREATE PROCEDURE CreateHL7Segment_CSS (IN ns NAMESPACE, IN OutRef REFERENCE)";
echo 	"\tBEGIN\n";
echo 	"\t\tDECLARE AssignValue CHARACTER '$assignValue';\n";
echo <<<ESQL
		CREATE LASTCHILD OF OutRef AS OutRef NAMESPACE ns NAME 'CSS';
		SET OutRef.ns:"CSS.1.StudyScheduledTimePoint".ns:"CWE.1" = AssignValue;
		SET OutRef.ns:"CSS.1.StudyScheduledTimePoint".ns:"CWE.2" = AssignValue;
		SET OutRef.ns:"CSS.1.StudyScheduledTimePoint".ns:"CWE.3" = AssignValue;
		SET OutRef.ns:"CSS.1.StudyScheduledTimePoint".ns:"CWE.4" = AssignValue;
		SET OutRef.ns:"CSS.1.StudyScheduledTimePoint".ns:"CWE.5" = AssignValue;
		SET OutRef.ns:"CSS.1.StudyScheduledTimePoint".ns:"CWE.6" = AssignValue;
		SET OutRef.ns:"CSS.1.StudyScheduledTimePoint".ns:"CWE.7" = AssignValue;
		SET OutRef.ns:"CSS.1.StudyScheduledTimePoint".ns:"CWE.8" = AssignValue;
		SET OutRef.ns:"CSS.1.StudyScheduledTimePoint".ns:"CWE.9" = AssignValue;
		SET OutRef.ns:"CSS.1.StudyScheduledTimePoint".ns:"CWE.10" = AssignValue;
		SET OutRef.ns:"CSS.1.StudyScheduledTimePoint".ns:"CWE.11" = AssignValue;
		SET OutRef.ns:"CSS.1.StudyScheduledTimePoint".ns:"CWE.12" = AssignValue;
		SET OutRef.ns:"CSS.1.StudyScheduledTimePoint".ns:"CWE.13" = AssignValue;
		SET OutRef.ns:"CSS.1.StudyScheduledTimePoint".ns:"CWE.14" = AssignValue;
		SET OutRef.ns:"CSS.1.StudyScheduledTimePoint".ns:"CWE.15" = AssignValue;
		SET OutRef.ns:"CSS.1.StudyScheduledTimePoint".ns:"CWE.16" = AssignValue;
		SET OutRef.ns:"CSS.1.StudyScheduledTimePoint".ns:"CWE.17" = AssignValue;
		SET OutRef.ns:"CSS.1.StudyScheduledTimePoint".ns:"CWE.18" = AssignValue;
		SET OutRef.ns:"CSS.1.StudyScheduledTimePoint".ns:"CWE.19" = AssignValue;
		SET OutRef.ns:"CSS.1.StudyScheduledTimePoint".ns:"CWE.20" = AssignValue;
		SET OutRef.ns:"CSS.1.StudyScheduledTimePoint".ns:"CWE.21" = AssignValue;
		SET OutRef.ns:"CSS.1.StudyScheduledTimePoint".ns:"CWE.22" = AssignValue;
		SET OutRef.ns:"CSS.2.StudyScheduledPatientTimePoint" = AssignValue;
		SET OutRef.ns:"CSS.3.StudyQualityControlCodes".ns:"CWE.1" = AssignValue;
		SET OutRef.ns:"CSS.3.StudyQualityControlCodes".ns:"CWE.2" = AssignValue;
		SET OutRef.ns:"CSS.3.StudyQualityControlCodes".ns:"CWE.3" = AssignValue;
		SET OutRef.ns:"CSS.3.StudyQualityControlCodes".ns:"CWE.4" = AssignValue;
		SET OutRef.ns:"CSS.3.StudyQualityControlCodes".ns:"CWE.5" = AssignValue;
		SET OutRef.ns:"CSS.3.StudyQualityControlCodes".ns:"CWE.6" = AssignValue;
		SET OutRef.ns:"CSS.3.StudyQualityControlCodes".ns:"CWE.7" = AssignValue;
		SET OutRef.ns:"CSS.3.StudyQualityControlCodes".ns:"CWE.8" = AssignValue;
		SET OutRef.ns:"CSS.3.StudyQualityControlCodes".ns:"CWE.9" = AssignValue;
		SET OutRef.ns:"CSS.3.StudyQualityControlCodes".ns:"CWE.10" = AssignValue;
		SET OutRef.ns:"CSS.3.StudyQualityControlCodes".ns:"CWE.11" = AssignValue;
		SET OutRef.ns:"CSS.3.StudyQualityControlCodes".ns:"CWE.12" = AssignValue;
		SET OutRef.ns:"CSS.3.StudyQualityControlCodes".ns:"CWE.13" = AssignValue;
		SET OutRef.ns:"CSS.3.StudyQualityControlCodes".ns:"CWE.14" = AssignValue;
		SET OutRef.ns:"CSS.3.StudyQualityControlCodes".ns:"CWE.15" = AssignValue;
		SET OutRef.ns:"CSS.3.StudyQualityControlCodes".ns:"CWE.16" = AssignValue;
		SET OutRef.ns:"CSS.3.StudyQualityControlCodes".ns:"CWE.17" = AssignValue;
		SET OutRef.ns:"CSS.3.StudyQualityControlCodes".ns:"CWE.18" = AssignValue;
		SET OutRef.ns:"CSS.3.StudyQualityControlCodes".ns:"CWE.19" = AssignValue;
		SET OutRef.ns:"CSS.3.StudyQualityControlCodes".ns:"CWE.20" = AssignValue;
		SET OutRef.ns:"CSS.3.StudyQualityControlCodes".ns:"CWE.21" = AssignValue;
		SET OutRef.ns:"CSS.3.StudyQualityControlCodes".ns:"CWE.22" = AssignValue;
		SET OutRef.ns:Remainder = AssignValue;
	END;
ESQL;
?>