<?php
$assignValue=$_MB['PP']['ppAssignValue'];
echo 	"CREATE PROCEDURE CreateHL7Segment_TCD (IN ns NAMESPACE, IN OutRef REFERENCE)";
echo 	"\tBEGIN\n";
echo 	"\t\tDECLARE AssignValue CHARACTER '$assignValue';\n";
echo <<<ESQL
		CREATE LASTCHILD OF OutRef AS OutRef NAMESPACE ns NAME 'TCD';
		SET OutRef.ns:"TCD.1.UniversalServiceIdentifier".ns:"CWE.1" = AssignValue;
		SET OutRef.ns:"TCD.1.UniversalServiceIdentifier".ns:"CWE.2" = AssignValue;
		SET OutRef.ns:"TCD.1.UniversalServiceIdentifier".ns:"CWE.3" = AssignValue;
		SET OutRef.ns:"TCD.1.UniversalServiceIdentifier".ns:"CWE.4" = AssignValue;
		SET OutRef.ns:"TCD.1.UniversalServiceIdentifier".ns:"CWE.5" = AssignValue;
		SET OutRef.ns:"TCD.1.UniversalServiceIdentifier".ns:"CWE.6" = AssignValue;
		SET OutRef.ns:"TCD.1.UniversalServiceIdentifier".ns:"CWE.7" = AssignValue;
		SET OutRef.ns:"TCD.1.UniversalServiceIdentifier".ns:"CWE.8" = AssignValue;
		SET OutRef.ns:"TCD.1.UniversalServiceIdentifier".ns:"CWE.9" = AssignValue;
		SET OutRef.ns:"TCD.1.UniversalServiceIdentifier".ns:"CWE.10" = AssignValue;
		SET OutRef.ns:"TCD.1.UniversalServiceIdentifier".ns:"CWE.11" = AssignValue;
		SET OutRef.ns:"TCD.1.UniversalServiceIdentifier".ns:"CWE.12" = AssignValue;
		SET OutRef.ns:"TCD.1.UniversalServiceIdentifier".ns:"CWE.13" = AssignValue;
		SET OutRef.ns:"TCD.1.UniversalServiceIdentifier".ns:"CWE.14" = AssignValue;
		SET OutRef.ns:"TCD.1.UniversalServiceIdentifier".ns:"CWE.15" = AssignValue;
		SET OutRef.ns:"TCD.1.UniversalServiceIdentifier".ns:"CWE.16" = AssignValue;
		SET OutRef.ns:"TCD.1.UniversalServiceIdentifier".ns:"CWE.17" = AssignValue;
		SET OutRef.ns:"TCD.1.UniversalServiceIdentifier".ns:"CWE.18" = AssignValue;
		SET OutRef.ns:"TCD.1.UniversalServiceIdentifier".ns:"CWE.19" = AssignValue;
		SET OutRef.ns:"TCD.1.UniversalServiceIdentifier".ns:"CWE.20" = AssignValue;
		SET OutRef.ns:"TCD.1.UniversalServiceIdentifier".ns:"CWE.21" = AssignValue;
		SET OutRef.ns:"TCD.1.UniversalServiceIdentifier".ns:"CWE.22" = AssignValue;
		SET OutRef.ns:"TCD.2.AutoDilutionFactor".ns:"SN.1" = AssignValue;
		SET OutRef.ns:"TCD.2.AutoDilutionFactor".ns:"SN.2" = AssignValue;
		SET OutRef.ns:"TCD.2.AutoDilutionFactor".ns:"SN.3" = AssignValue;
		SET OutRef.ns:"TCD.2.AutoDilutionFactor".ns:"SN.4" = AssignValue;
		SET OutRef.ns:"TCD.3.RerunDilutionFactor".ns:"SN.1" = AssignValue;
		SET OutRef.ns:"TCD.3.RerunDilutionFactor".ns:"SN.2" = AssignValue;
		SET OutRef.ns:"TCD.3.RerunDilutionFactor".ns:"SN.3" = AssignValue;
		SET OutRef.ns:"TCD.3.RerunDilutionFactor".ns:"SN.4" = AssignValue;
		SET OutRef.ns:"TCD.4.PreDilutionFactor".ns:"SN.1" = AssignValue;
		SET OutRef.ns:"TCD.4.PreDilutionFactor".ns:"SN.2" = AssignValue;
		SET OutRef.ns:"TCD.4.PreDilutionFactor".ns:"SN.3" = AssignValue;
		SET OutRef.ns:"TCD.4.PreDilutionFactor".ns:"SN.4" = AssignValue;
		SET OutRef.ns:"TCD.5.EndogenousContentofPreDilutionDiluent".ns:"SN.1" = AssignValue;
		SET OutRef.ns:"TCD.5.EndogenousContentofPreDilutionDiluent".ns:"SN.2" = AssignValue;
		SET OutRef.ns:"TCD.5.EndogenousContentofPreDilutionDiluent".ns:"SN.3" = AssignValue;
		SET OutRef.ns:"TCD.5.EndogenousContentofPreDilutionDiluent".ns:"SN.4" = AssignValue;
		SET OutRef.ns:"TCD.6.AutomaticRepeatAllowed" = AssignValue;
		SET OutRef.ns:"TCD.7.ReflexAllowed" = AssignValue;
		SET OutRef.ns:"TCD.8.AnalyteRepeatStatus".ns:"CWE.1" = AssignValue;
		SET OutRef.ns:"TCD.8.AnalyteRepeatStatus".ns:"CWE.2" = AssignValue;
		SET OutRef.ns:"TCD.8.AnalyteRepeatStatus".ns:"CWE.3" = AssignValue;
		SET OutRef.ns:"TCD.8.AnalyteRepeatStatus".ns:"CWE.4" = AssignValue;
		SET OutRef.ns:"TCD.8.AnalyteRepeatStatus".ns:"CWE.5" = AssignValue;
		SET OutRef.ns:"TCD.8.AnalyteRepeatStatus".ns:"CWE.6" = AssignValue;
		SET OutRef.ns:"TCD.8.AnalyteRepeatStatus".ns:"CWE.7" = AssignValue;
		SET OutRef.ns:"TCD.8.AnalyteRepeatStatus".ns:"CWE.8" = AssignValue;
		SET OutRef.ns:"TCD.8.AnalyteRepeatStatus".ns:"CWE.9" = AssignValue;
		SET OutRef.ns:"TCD.8.AnalyteRepeatStatus".ns:"CWE.10" = AssignValue;
		SET OutRef.ns:"TCD.8.AnalyteRepeatStatus".ns:"CWE.11" = AssignValue;
		SET OutRef.ns:"TCD.8.AnalyteRepeatStatus".ns:"CWE.12" = AssignValue;
		SET OutRef.ns:"TCD.8.AnalyteRepeatStatus".ns:"CWE.13" = AssignValue;
		SET OutRef.ns:"TCD.8.AnalyteRepeatStatus".ns:"CWE.14" = AssignValue;
		SET OutRef.ns:"TCD.8.AnalyteRepeatStatus".ns:"CWE.15" = AssignValue;
		SET OutRef.ns:"TCD.8.AnalyteRepeatStatus".ns:"CWE.16" = AssignValue;
		SET OutRef.ns:"TCD.8.AnalyteRepeatStatus".ns:"CWE.17" = AssignValue;
		SET OutRef.ns:"TCD.8.AnalyteRepeatStatus".ns:"CWE.18" = AssignValue;
		SET OutRef.ns:"TCD.8.AnalyteRepeatStatus".ns:"CWE.19" = AssignValue;
		SET OutRef.ns:"TCD.8.AnalyteRepeatStatus".ns:"CWE.20" = AssignValue;
		SET OutRef.ns:"TCD.8.AnalyteRepeatStatus".ns:"CWE.21" = AssignValue;
		SET OutRef.ns:"TCD.8.AnalyteRepeatStatus".ns:"CWE.22" = AssignValue;
		SET OutRef.ns:Remainder = AssignValue;
	END;
ESQL;
?>