<?php
$assignValue=$_MB['PP']['ppAssignValue'];
echo 	"CREATE PROCEDURE CreateHL7Segment_DB1 (IN ns NAMESPACE, IN OutRef REFERENCE)";
echo 	"\tBEGIN\n";
echo 	"\t\tDECLARE AssignValue CHARACTER '$assignValue';\n";
echo <<<ESQL
		CREATE LASTCHILD OF OutRef AS OutRef NAMESPACE ns NAME 'DB1';
		SET OutRef.ns:"DB1.1.SetIDDB1" = AssignValue;
		SET OutRef.ns:"DB1.2.DisabledPersonCode".ns:"CWE.1" = AssignValue;
		SET OutRef.ns:"DB1.2.DisabledPersonCode".ns:"CWE.2" = AssignValue;
		SET OutRef.ns:"DB1.2.DisabledPersonCode".ns:"CWE.3" = AssignValue;
		SET OutRef.ns:"DB1.2.DisabledPersonCode".ns:"CWE.4" = AssignValue;
		SET OutRef.ns:"DB1.2.DisabledPersonCode".ns:"CWE.5" = AssignValue;
		SET OutRef.ns:"DB1.2.DisabledPersonCode".ns:"CWE.6" = AssignValue;
		SET OutRef.ns:"DB1.2.DisabledPersonCode".ns:"CWE.7" = AssignValue;
		SET OutRef.ns:"DB1.2.DisabledPersonCode".ns:"CWE.8" = AssignValue;
		SET OutRef.ns:"DB1.2.DisabledPersonCode".ns:"CWE.9" = AssignValue;
		SET OutRef.ns:"DB1.2.DisabledPersonCode".ns:"CWE.10" = AssignValue;
		SET OutRef.ns:"DB1.2.DisabledPersonCode".ns:"CWE.11" = AssignValue;
		SET OutRef.ns:"DB1.2.DisabledPersonCode".ns:"CWE.12" = AssignValue;
		SET OutRef.ns:"DB1.2.DisabledPersonCode".ns:"CWE.13" = AssignValue;
		SET OutRef.ns:"DB1.2.DisabledPersonCode".ns:"CWE.14" = AssignValue;
		SET OutRef.ns:"DB1.2.DisabledPersonCode".ns:"CWE.15" = AssignValue;
		SET OutRef.ns:"DB1.2.DisabledPersonCode".ns:"CWE.16" = AssignValue;
		SET OutRef.ns:"DB1.2.DisabledPersonCode".ns:"CWE.17" = AssignValue;
		SET OutRef.ns:"DB1.2.DisabledPersonCode".ns:"CWE.18" = AssignValue;
		SET OutRef.ns:"DB1.2.DisabledPersonCode".ns:"CWE.19" = AssignValue;
		SET OutRef.ns:"DB1.2.DisabledPersonCode".ns:"CWE.20" = AssignValue;
		SET OutRef.ns:"DB1.2.DisabledPersonCode".ns:"CWE.21" = AssignValue;
		SET OutRef.ns:"DB1.2.DisabledPersonCode".ns:"CWE.22" = AssignValue;
		SET OutRef.ns:"DB1.3.DisabledPersonIdentifier".ns:"CX.1" = AssignValue;
		SET OutRef.ns:"DB1.3.DisabledPersonIdentifier".ns:"CX.2" = AssignValue;
		SET OutRef.ns:"DB1.3.DisabledPersonIdentifier".ns:"CX.3" = AssignValue;
		SET OutRef.ns:"DB1.3.DisabledPersonIdentifier".ns:"CX.4".ns:"HD.1" = AssignValue;
		SET OutRef.ns:"DB1.3.DisabledPersonIdentifier".ns:"CX.4".ns:"HD.2" = AssignValue;
		SET OutRef.ns:"DB1.3.DisabledPersonIdentifier".ns:"CX.4".ns:"HD.3" = AssignValue;
		SET OutRef.ns:"DB1.3.DisabledPersonIdentifier".ns:"CX.5" = AssignValue;
		SET OutRef.ns:"DB1.3.DisabledPersonIdentifier".ns:"CX.6".ns:"HD.1" = AssignValue;
		SET OutRef.ns:"DB1.3.DisabledPersonIdentifier".ns:"CX.6".ns:"HD.2" = AssignValue;
		SET OutRef.ns:"DB1.3.DisabledPersonIdentifier".ns:"CX.6".ns:"HD.3" = AssignValue;
		SET OutRef.ns:"DB1.3.DisabledPersonIdentifier".ns:"CX.7" = AssignValue;
		SET OutRef.ns:"DB1.3.DisabledPersonIdentifier".ns:"CX.8" = AssignValue;
		SET OutRef.ns:"DB1.3.DisabledPersonIdentifier".ns:"CX.9".ns:"CWE.1" = AssignValue;
		SET OutRef.ns:"DB1.3.DisabledPersonIdentifier".ns:"CX.9".ns:"CWE.2" = AssignValue;
		SET OutRef.ns:"DB1.3.DisabledPersonIdentifier".ns:"CX.9".ns:"CWE.3" = AssignValue;
		SET OutRef.ns:"DB1.3.DisabledPersonIdentifier".ns:"CX.9".ns:"CWE.4" = AssignValue;
		SET OutRef.ns:"DB1.3.DisabledPersonIdentifier".ns:"CX.9".ns:"CWE.5" = AssignValue;
		SET OutRef.ns:"DB1.3.DisabledPersonIdentifier".ns:"CX.9".ns:"CWE.6" = AssignValue;
		SET OutRef.ns:"DB1.3.DisabledPersonIdentifier".ns:"CX.9".ns:"CWE.7" = AssignValue;
		SET OutRef.ns:"DB1.3.DisabledPersonIdentifier".ns:"CX.9".ns:"CWE.8" = AssignValue;
		SET OutRef.ns:"DB1.3.DisabledPersonIdentifier".ns:"CX.9".ns:"CWE.9" = AssignValue;
		SET OutRef.ns:"DB1.3.DisabledPersonIdentifier".ns:"CX.9".ns:"CWE.10" = AssignValue;
		SET OutRef.ns:"DB1.3.DisabledPersonIdentifier".ns:"CX.9".ns:"CWE.11" = AssignValue;
		SET OutRef.ns:"DB1.3.DisabledPersonIdentifier".ns:"CX.9".ns:"CWE.12" = AssignValue;
		SET OutRef.ns:"DB1.3.DisabledPersonIdentifier".ns:"CX.9".ns:"CWE.13" = AssignValue;
		SET OutRef.ns:"DB1.3.DisabledPersonIdentifier".ns:"CX.9".ns:"CWE.14" = AssignValue;
		SET OutRef.ns:"DB1.3.DisabledPersonIdentifier".ns:"CX.9".ns:"CWE.15" = AssignValue;
		SET OutRef.ns:"DB1.3.DisabledPersonIdentifier".ns:"CX.9".ns:"CWE.16" = AssignValue;
		SET OutRef.ns:"DB1.3.DisabledPersonIdentifier".ns:"CX.9".ns:"CWE.17" = AssignValue;
		SET OutRef.ns:"DB1.3.DisabledPersonIdentifier".ns:"CX.9".ns:"CWE.18" = AssignValue;
		SET OutRef.ns:"DB1.3.DisabledPersonIdentifier".ns:"CX.9".ns:"CWE.19" = AssignValue;
		SET OutRef.ns:"DB1.3.DisabledPersonIdentifier".ns:"CX.9".ns:"CWE.20" = AssignValue;
		SET OutRef.ns:"DB1.3.DisabledPersonIdentifier".ns:"CX.9".ns:"CWE.21" = AssignValue;
		SET OutRef.ns:"DB1.3.DisabledPersonIdentifier".ns:"CX.9".ns:"CWE.22" = AssignValue;
		SET OutRef.ns:"DB1.3.DisabledPersonIdentifier".ns:"CX.10".ns:"CWE.1" = AssignValue;
		SET OutRef.ns:"DB1.3.DisabledPersonIdentifier".ns:"CX.10".ns:"CWE.2" = AssignValue;
		SET OutRef.ns:"DB1.3.DisabledPersonIdentifier".ns:"CX.10".ns:"CWE.3" = AssignValue;
		SET OutRef.ns:"DB1.3.DisabledPersonIdentifier".ns:"CX.10".ns:"CWE.4" = AssignValue;
		SET OutRef.ns:"DB1.3.DisabledPersonIdentifier".ns:"CX.10".ns:"CWE.5" = AssignValue;
		SET OutRef.ns:"DB1.3.DisabledPersonIdentifier".ns:"CX.10".ns:"CWE.6" = AssignValue;
		SET OutRef.ns:"DB1.3.DisabledPersonIdentifier".ns:"CX.10".ns:"CWE.7" = AssignValue;
		SET OutRef.ns:"DB1.3.DisabledPersonIdentifier".ns:"CX.10".ns:"CWE.8" = AssignValue;
		SET OutRef.ns:"DB1.3.DisabledPersonIdentifier".ns:"CX.10".ns:"CWE.9" = AssignValue;
		SET OutRef.ns:"DB1.3.DisabledPersonIdentifier".ns:"CX.10".ns:"CWE.10" = AssignValue;
		SET OutRef.ns:"DB1.3.DisabledPersonIdentifier".ns:"CX.10".ns:"CWE.11" = AssignValue;
		SET OutRef.ns:"DB1.3.DisabledPersonIdentifier".ns:"CX.10".ns:"CWE.12" = AssignValue;
		SET OutRef.ns:"DB1.3.DisabledPersonIdentifier".ns:"CX.10".ns:"CWE.13" = AssignValue;
		SET OutRef.ns:"DB1.3.DisabledPersonIdentifier".ns:"CX.10".ns:"CWE.14" = AssignValue;
		SET OutRef.ns:"DB1.3.DisabledPersonIdentifier".ns:"CX.10".ns:"CWE.15" = AssignValue;
		SET OutRef.ns:"DB1.3.DisabledPersonIdentifier".ns:"CX.10".ns:"CWE.16" = AssignValue;
		SET OutRef.ns:"DB1.3.DisabledPersonIdentifier".ns:"CX.10".ns:"CWE.17" = AssignValue;
		SET OutRef.ns:"DB1.3.DisabledPersonIdentifier".ns:"CX.10".ns:"CWE.18" = AssignValue;
		SET OutRef.ns:"DB1.3.DisabledPersonIdentifier".ns:"CX.10".ns:"CWE.19" = AssignValue;
		SET OutRef.ns:"DB1.3.DisabledPersonIdentifier".ns:"CX.10".ns:"CWE.20" = AssignValue;
		SET OutRef.ns:"DB1.3.DisabledPersonIdentifier".ns:"CX.10".ns:"CWE.21" = AssignValue;
		SET OutRef.ns:"DB1.3.DisabledPersonIdentifier".ns:"CX.10".ns:"CWE.22" = AssignValue;
		SET OutRef.ns:"DB1.3.DisabledPersonIdentifier".ns:"CX.11" = AssignValue;
		SET OutRef.ns:"DB1.3.DisabledPersonIdentifier".ns:"CX.12" = AssignValue;
		SET OutRef.ns:"DB1.4.DisabilityIndicator" = AssignValue;
		SET OutRef.ns:"DB1.5.DisabilityStartDate" = AssignValue;
		SET OutRef.ns:"DB1.6.DisabilityEndDate" = AssignValue;
		SET OutRef.ns:"DB1.7.DisabilityReturntoWorkDate" = AssignValue;
		SET OutRef.ns:"DB1.8.DisabilityUnabletoWorkDate" = AssignValue;
		SET OutRef.ns:Remainder = AssignValue;
	END;
ESQL;
?>