CREATE TABLE WMB_BUSTRANS (
		ID VARCHAR2(100) NOT NULL,
        FIRST_SEEN_TIMESTAMP VARCHAR2(100), 
        LAST_SEEN_TIMESTAMP VARCHAR2(100),   
		BTD_NAME VARCHAR2(100) NOT NULL, 
		STATUS VARCHAR2(1), 
        WMB_MSGKEY VARCHAR2(100) NOT NULL,
        SEQ_NO INTEGER NOT NULL, 
        SEQ_TIME NUMBER, 
        ROLE INTEGER,
        UNIQUE_FLOW_NAME VARCHAR2(500),
		primary key(ID,BTD_NAME,SEQ_NO)
	);
