<?php
$assignValue=$_MB['PP']['ppAssignValue'];
echo <<<MAP
<?xml version="1.0" encoding="UTF-8"?>
<mappingRoot domainID="com.ibm.msl.mapping.xml" domainIDExtension="mb" mainMap="false" targetNamespace="default" version="8.0.3.0" xmlns="http://www.ibm.com/2008/ccl/Mapping" xmlns:map="default">
	<input path="jar:file://!com/ibm/etools/mft/map/xsds/predefined/BlobMessage.xsd"/>
	<output path="/segments.xsd"/>
	<generation engine="xquery"/>
	<mappingDeclaration name="CreateHL7Segment_QRF">
		<input path="BLOB"/>
		<output namespace="urn:hl7-org:v2xml" path="QRF"/>
MAP;
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"QRF.1.WhereSubjectFilter\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"QRF.2.WhenDataStartDateTime/TS.1\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"QRF.2.WhenDataStartDateTime/TS.2\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"QRF.3.WhenDataEndDateTime/TS.1\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"QRF.3.WhenDataEndDateTime/TS.2\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"QRF.4.WhatUserQualifier\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"QRF.5.OtherQRYSubjectFilter\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"QRF.6.WhichDateTimeQualifier\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"QRF.7.WhichDateTimeStatusQualifier\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"QRF.8.DateTimeSelectionQualifier\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"QRF.9.WhenQuantityTimingQualifier/TQ.1/CQ.1\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"QRF.9.WhenQuantityTimingQualifier/TQ.1/CQ.2/CWE.1\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"QRF.9.WhenQuantityTimingQualifier/TQ.1/CQ.2/CWE.2\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"QRF.9.WhenQuantityTimingQualifier/TQ.1/CQ.2/CWE.3\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"QRF.9.WhenQuantityTimingQualifier/TQ.1/CQ.2/CWE.4\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"QRF.9.WhenQuantityTimingQualifier/TQ.1/CQ.2/CWE.5\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"QRF.9.WhenQuantityTimingQualifier/TQ.1/CQ.2/CWE.6\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"QRF.9.WhenQuantityTimingQualifier/TQ.1/CQ.2/CWE.7\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"QRF.9.WhenQuantityTimingQualifier/TQ.1/CQ.2/CWE.8\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"QRF.9.WhenQuantityTimingQualifier/TQ.1/CQ.2/CWE.9\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"QRF.9.WhenQuantityTimingQualifier/TQ.1/CQ.2/CWE.10\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"QRF.9.WhenQuantityTimingQualifier/TQ.1/CQ.2/CWE.11\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"QRF.9.WhenQuantityTimingQualifier/TQ.1/CQ.2/CWE.12\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"QRF.9.WhenQuantityTimingQualifier/TQ.1/CQ.2/CWE.13\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"QRF.9.WhenQuantityTimingQualifier/TQ.1/CQ.2/CWE.14\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"QRF.9.WhenQuantityTimingQualifier/TQ.1/CQ.2/CWE.15\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"QRF.9.WhenQuantityTimingQualifier/TQ.1/CQ.2/CWE.16\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"QRF.9.WhenQuantityTimingQualifier/TQ.1/CQ.2/CWE.17\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"QRF.9.WhenQuantityTimingQualifier/TQ.1/CQ.2/CWE.18\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"QRF.9.WhenQuantityTimingQualifier/TQ.1/CQ.2/CWE.19\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"QRF.9.WhenQuantityTimingQualifier/TQ.1/CQ.2/CWE.20\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"QRF.9.WhenQuantityTimingQualifier/TQ.1/CQ.2/CWE.21\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"QRF.9.WhenQuantityTimingQualifier/TQ.1/CQ.2/CWE.22\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"QRF.9.WhenQuantityTimingQualifier/TQ.2/RI.1/CWE.1\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"QRF.9.WhenQuantityTimingQualifier/TQ.2/RI.1/CWE.2\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"QRF.9.WhenQuantityTimingQualifier/TQ.2/RI.1/CWE.3\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"QRF.9.WhenQuantityTimingQualifier/TQ.2/RI.1/CWE.4\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"QRF.9.WhenQuantityTimingQualifier/TQ.2/RI.1/CWE.5\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"QRF.9.WhenQuantityTimingQualifier/TQ.2/RI.1/CWE.6\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"QRF.9.WhenQuantityTimingQualifier/TQ.2/RI.1/CWE.7\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"QRF.9.WhenQuantityTimingQualifier/TQ.2/RI.1/CWE.8\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"QRF.9.WhenQuantityTimingQualifier/TQ.2/RI.1/CWE.9\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"QRF.9.WhenQuantityTimingQualifier/TQ.2/RI.1/CWE.10\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"QRF.9.WhenQuantityTimingQualifier/TQ.2/RI.1/CWE.11\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"QRF.9.WhenQuantityTimingQualifier/TQ.2/RI.1/CWE.12\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"QRF.9.WhenQuantityTimingQualifier/TQ.2/RI.1/CWE.13\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"QRF.9.WhenQuantityTimingQualifier/TQ.2/RI.1/CWE.14\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"QRF.9.WhenQuantityTimingQualifier/TQ.2/RI.1/CWE.15\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"QRF.9.WhenQuantityTimingQualifier/TQ.2/RI.1/CWE.16\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"QRF.9.WhenQuantityTimingQualifier/TQ.2/RI.1/CWE.17\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"QRF.9.WhenQuantityTimingQualifier/TQ.2/RI.1/CWE.18\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"QRF.9.WhenQuantityTimingQualifier/TQ.2/RI.1/CWE.19\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"QRF.9.WhenQuantityTimingQualifier/TQ.2/RI.1/CWE.20\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"QRF.9.WhenQuantityTimingQualifier/TQ.2/RI.1/CWE.21\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"QRF.9.WhenQuantityTimingQualifier/TQ.2/RI.1/CWE.22\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"QRF.9.WhenQuantityTimingQualifier/TQ.2/RI.2\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"QRF.9.WhenQuantityTimingQualifier/TQ.3\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"QRF.9.WhenQuantityTimingQualifier/TQ.4/TS.1\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"QRF.9.WhenQuantityTimingQualifier/TQ.4/TS.2\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"QRF.9.WhenQuantityTimingQualifier/TQ.5/TS.1\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"QRF.9.WhenQuantityTimingQualifier/TQ.5/TS.2\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"QRF.9.WhenQuantityTimingQualifier/TQ.6\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"QRF.9.WhenQuantityTimingQualifier/TQ.7\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"QRF.9.WhenQuantityTimingQualifier/TQ.8\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"QRF.9.WhenQuantityTimingQualifier/TQ.9\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"QRF.9.WhenQuantityTimingQualifier/TQ.10/OSD.1\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"QRF.9.WhenQuantityTimingQualifier/TQ.10/OSD.2\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"QRF.9.WhenQuantityTimingQualifier/TQ.10/OSD.3\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"QRF.9.WhenQuantityTimingQualifier/TQ.10/OSD.4\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"QRF.9.WhenQuantityTimingQualifier/TQ.10/OSD.5\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"QRF.9.WhenQuantityTimingQualifier/TQ.10/OSD.6\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"QRF.9.WhenQuantityTimingQualifier/TQ.10/OSD.7\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"QRF.9.WhenQuantityTimingQualifier/TQ.10/OSD.8\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"QRF.9.WhenQuantityTimingQualifier/TQ.10/OSD.9\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"QRF.9.WhenQuantityTimingQualifier/TQ.10/OSD.10\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"QRF.9.WhenQuantityTimingQualifier/TQ.10/OSD.11\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"QRF.9.WhenQuantityTimingQualifier/TQ.12\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"QRF.10.SearchConfidenceThreshold\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"Remainder\"/>\n";
echo			"</assign>\n";
echo	"</mappingDeclaration>\n";
echo	"</mappingRoot>\n";
?>