<?php
$assignValue=$_MB['PP']['ppAssignValue'];
echo <<<MAP
<?xml version="1.0" encoding="UTF-8"?>
<mappingRoot domainID="com.ibm.msl.mapping.xml" domainIDExtension="mb" mainMap="false" targetNamespace="default" version="8.0.3.0" xmlns="http://www.ibm.com/2008/ccl/Mapping" xmlns:map="default">
	<input path="jar:file://!com/ibm/etools/mft/map/xsds/predefined/BlobMessage.xsd"/>
	<output path="/segments.xsd"/>
	<generation engine="xquery"/>
	<mappingDeclaration name="CreateHL7Segment_OM2">
		<input path="BLOB"/>
		<output namespace="urn:hl7-org:v2xml" path="OM2"/>
MAP;
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.1.SequenceNumberTestObservationMasterFile\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.2.UnitsofMeasure/CWE.1\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.2.UnitsofMeasure/CWE.2\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.2.UnitsofMeasure/CWE.3\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.2.UnitsofMeasure/CWE.4\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.2.UnitsofMeasure/CWE.5\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.2.UnitsofMeasure/CWE.6\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.2.UnitsofMeasure/CWE.7\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.2.UnitsofMeasure/CWE.8\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.2.UnitsofMeasure/CWE.9\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.2.UnitsofMeasure/CWE.10\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.2.UnitsofMeasure/CWE.11\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.2.UnitsofMeasure/CWE.12\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.2.UnitsofMeasure/CWE.13\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.2.UnitsofMeasure/CWE.14\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.2.UnitsofMeasure/CWE.15\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.2.UnitsofMeasure/CWE.16\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.2.UnitsofMeasure/CWE.17\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.2.UnitsofMeasure/CWE.18\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.2.UnitsofMeasure/CWE.19\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.2.UnitsofMeasure/CWE.20\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.2.UnitsofMeasure/CWE.21\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.2.UnitsofMeasure/CWE.22\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.3.RangeofDecimalPrecision\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.4.CorrespondingSIUnitsofMeasure/CWE.1\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.4.CorrespondingSIUnitsofMeasure/CWE.2\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.4.CorrespondingSIUnitsofMeasure/CWE.3\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.4.CorrespondingSIUnitsofMeasure/CWE.4\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.4.CorrespondingSIUnitsofMeasure/CWE.5\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.4.CorrespondingSIUnitsofMeasure/CWE.6\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.4.CorrespondingSIUnitsofMeasure/CWE.7\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.4.CorrespondingSIUnitsofMeasure/CWE.8\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.4.CorrespondingSIUnitsofMeasure/CWE.9\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.4.CorrespondingSIUnitsofMeasure/CWE.10\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.4.CorrespondingSIUnitsofMeasure/CWE.11\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.4.CorrespondingSIUnitsofMeasure/CWE.12\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.4.CorrespondingSIUnitsofMeasure/CWE.13\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.4.CorrespondingSIUnitsofMeasure/CWE.14\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.4.CorrespondingSIUnitsofMeasure/CWE.15\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.4.CorrespondingSIUnitsofMeasure/CWE.16\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.4.CorrespondingSIUnitsofMeasure/CWE.17\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.4.CorrespondingSIUnitsofMeasure/CWE.18\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.4.CorrespondingSIUnitsofMeasure/CWE.19\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.4.CorrespondingSIUnitsofMeasure/CWE.20\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.4.CorrespondingSIUnitsofMeasure/CWE.21\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.4.CorrespondingSIUnitsofMeasure/CWE.22\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.5.SIConversionFactor\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.6.ReferenceNormalRangeOrdinalandContinuousObservations/RFR.1/NR.1\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.6.ReferenceNormalRangeOrdinalandContinuousObservations/RFR.1/NR.2\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.6.ReferenceNormalRangeOrdinalandContinuousObservations/RFR.2/CWE.1\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.6.ReferenceNormalRangeOrdinalandContinuousObservations/RFR.2/CWE.2\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.6.ReferenceNormalRangeOrdinalandContinuousObservations/RFR.2/CWE.3\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.6.ReferenceNormalRangeOrdinalandContinuousObservations/RFR.2/CWE.4\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.6.ReferenceNormalRangeOrdinalandContinuousObservations/RFR.2/CWE.5\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.6.ReferenceNormalRangeOrdinalandContinuousObservations/RFR.2/CWE.6\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.6.ReferenceNormalRangeOrdinalandContinuousObservations/RFR.2/CWE.7\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.6.ReferenceNormalRangeOrdinalandContinuousObservations/RFR.2/CWE.8\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.6.ReferenceNormalRangeOrdinalandContinuousObservations/RFR.2/CWE.9\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.6.ReferenceNormalRangeOrdinalandContinuousObservations/RFR.2/CWE.10\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.6.ReferenceNormalRangeOrdinalandContinuousObservations/RFR.2/CWE.11\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.6.ReferenceNormalRangeOrdinalandContinuousObservations/RFR.2/CWE.12\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.6.ReferenceNormalRangeOrdinalandContinuousObservations/RFR.2/CWE.13\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.6.ReferenceNormalRangeOrdinalandContinuousObservations/RFR.2/CWE.14\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.6.ReferenceNormalRangeOrdinalandContinuousObservations/RFR.2/CWE.15\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.6.ReferenceNormalRangeOrdinalandContinuousObservations/RFR.2/CWE.16\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.6.ReferenceNormalRangeOrdinalandContinuousObservations/RFR.2/CWE.17\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.6.ReferenceNormalRangeOrdinalandContinuousObservations/RFR.2/CWE.18\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.6.ReferenceNormalRangeOrdinalandContinuousObservations/RFR.2/CWE.19\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.6.ReferenceNormalRangeOrdinalandContinuousObservations/RFR.2/CWE.20\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.6.ReferenceNormalRangeOrdinalandContinuousObservations/RFR.2/CWE.21\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.6.ReferenceNormalRangeOrdinalandContinuousObservations/RFR.2/CWE.22\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.6.ReferenceNormalRangeOrdinalandContinuousObservations/RFR.3/NR.1\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.6.ReferenceNormalRangeOrdinalandContinuousObservations/RFR.3/NR.2\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.6.ReferenceNormalRangeOrdinalandContinuousObservations/RFR.4/NR.1\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.6.ReferenceNormalRangeOrdinalandContinuousObservations/RFR.4/NR.2\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.6.ReferenceNormalRangeOrdinalandContinuousObservations/RFR.5\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.6.ReferenceNormalRangeOrdinalandContinuousObservations/RFR.6\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.6.ReferenceNormalRangeOrdinalandContinuousObservations/RFR.7\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.7.CriticalRangeforOrdinalandContinuousObservations/RFR.1/NR.1\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.7.CriticalRangeforOrdinalandContinuousObservations/RFR.1/NR.2\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.7.CriticalRangeforOrdinalandContinuousObservations/RFR.2/CWE.1\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.7.CriticalRangeforOrdinalandContinuousObservations/RFR.2/CWE.2\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.7.CriticalRangeforOrdinalandContinuousObservations/RFR.2/CWE.3\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.7.CriticalRangeforOrdinalandContinuousObservations/RFR.2/CWE.4\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.7.CriticalRangeforOrdinalandContinuousObservations/RFR.2/CWE.5\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.7.CriticalRangeforOrdinalandContinuousObservations/RFR.2/CWE.6\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.7.CriticalRangeforOrdinalandContinuousObservations/RFR.2/CWE.7\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.7.CriticalRangeforOrdinalandContinuousObservations/RFR.2/CWE.8\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.7.CriticalRangeforOrdinalandContinuousObservations/RFR.2/CWE.9\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.7.CriticalRangeforOrdinalandContinuousObservations/RFR.2/CWE.10\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.7.CriticalRangeforOrdinalandContinuousObservations/RFR.2/CWE.11\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.7.CriticalRangeforOrdinalandContinuousObservations/RFR.2/CWE.12\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.7.CriticalRangeforOrdinalandContinuousObservations/RFR.2/CWE.13\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.7.CriticalRangeforOrdinalandContinuousObservations/RFR.2/CWE.14\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.7.CriticalRangeforOrdinalandContinuousObservations/RFR.2/CWE.15\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.7.CriticalRangeforOrdinalandContinuousObservations/RFR.2/CWE.16\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.7.CriticalRangeforOrdinalandContinuousObservations/RFR.2/CWE.17\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.7.CriticalRangeforOrdinalandContinuousObservations/RFR.2/CWE.18\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.7.CriticalRangeforOrdinalandContinuousObservations/RFR.2/CWE.19\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.7.CriticalRangeforOrdinalandContinuousObservations/RFR.2/CWE.20\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.7.CriticalRangeforOrdinalandContinuousObservations/RFR.2/CWE.21\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.7.CriticalRangeforOrdinalandContinuousObservations/RFR.2/CWE.22\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.7.CriticalRangeforOrdinalandContinuousObservations/RFR.3/NR.1\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.7.CriticalRangeforOrdinalandContinuousObservations/RFR.3/NR.2\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.7.CriticalRangeforOrdinalandContinuousObservations/RFR.4/NR.1\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.7.CriticalRangeforOrdinalandContinuousObservations/RFR.4/NR.2\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.7.CriticalRangeforOrdinalandContinuousObservations/RFR.5\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.7.CriticalRangeforOrdinalandContinuousObservations/RFR.6\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.7.CriticalRangeforOrdinalandContinuousObservations/RFR.7\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.8.AbsoluteRangeforOrdinalandContinuousObservations/RFR.1/NR.1\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.8.AbsoluteRangeforOrdinalandContinuousObservations/RFR.1/NR.2\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.8.AbsoluteRangeforOrdinalandContinuousObservations/RFR.2/CWE.1\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.8.AbsoluteRangeforOrdinalandContinuousObservations/RFR.2/CWE.2\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.8.AbsoluteRangeforOrdinalandContinuousObservations/RFR.2/CWE.3\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.8.AbsoluteRangeforOrdinalandContinuousObservations/RFR.2/CWE.4\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.8.AbsoluteRangeforOrdinalandContinuousObservations/RFR.2/CWE.5\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.8.AbsoluteRangeforOrdinalandContinuousObservations/RFR.2/CWE.6\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.8.AbsoluteRangeforOrdinalandContinuousObservations/RFR.2/CWE.7\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.8.AbsoluteRangeforOrdinalandContinuousObservations/RFR.2/CWE.8\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.8.AbsoluteRangeforOrdinalandContinuousObservations/RFR.2/CWE.9\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.8.AbsoluteRangeforOrdinalandContinuousObservations/RFR.2/CWE.10\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.8.AbsoluteRangeforOrdinalandContinuousObservations/RFR.2/CWE.11\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.8.AbsoluteRangeforOrdinalandContinuousObservations/RFR.2/CWE.12\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.8.AbsoluteRangeforOrdinalandContinuousObservations/RFR.2/CWE.13\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.8.AbsoluteRangeforOrdinalandContinuousObservations/RFR.2/CWE.14\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.8.AbsoluteRangeforOrdinalandContinuousObservations/RFR.2/CWE.15\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.8.AbsoluteRangeforOrdinalandContinuousObservations/RFR.2/CWE.16\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.8.AbsoluteRangeforOrdinalandContinuousObservations/RFR.2/CWE.17\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.8.AbsoluteRangeforOrdinalandContinuousObservations/RFR.2/CWE.18\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.8.AbsoluteRangeforOrdinalandContinuousObservations/RFR.2/CWE.19\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.8.AbsoluteRangeforOrdinalandContinuousObservations/RFR.2/CWE.20\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.8.AbsoluteRangeforOrdinalandContinuousObservations/RFR.2/CWE.21\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.8.AbsoluteRangeforOrdinalandContinuousObservations/RFR.2/CWE.22\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.8.AbsoluteRangeforOrdinalandContinuousObservations/RFR.3/NR.1\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.8.AbsoluteRangeforOrdinalandContinuousObservations/RFR.3/NR.2\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.8.AbsoluteRangeforOrdinalandContinuousObservations/RFR.4/NR.1\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.8.AbsoluteRangeforOrdinalandContinuousObservations/RFR.4/NR.2\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.8.AbsoluteRangeforOrdinalandContinuousObservations/RFR.5\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.8.AbsoluteRangeforOrdinalandContinuousObservations/RFR.6\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.8.AbsoluteRangeforOrdinalandContinuousObservations/RFR.7\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.9.DeltaCheckCriteria/DLT.1/NR.1\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.9.DeltaCheckCriteria/DLT.1/NR.2\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.9.DeltaCheckCriteria/DLT.2\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.9.DeltaCheckCriteria/DLT.3\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.9.DeltaCheckCriteria/DLT.4\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"OM2.10.MinimumMeaningfulIncrements\"/>\n";
echo			"</assign>\n";
echo			"<assign value=\"$assignValue\">\n";
echo				"<output path=\"Remainder\"/>\n";
echo			"</assign>\n";
echo	"</mappingDeclaration>\n";
echo	"</mappingRoot>\n";
?>